import type { SoftwareEntity } from "@/types/entities"

const entities: Record<string, SoftwareEntity> = {
  "1password": {
    slug: "1password",
    name: "1Password",
    company: {
      legalName: "AgileBits Inc.",
      website: "https://1password.com",
      founded: 2005,
      headquarters: "Toronto, Ontario, Canada",
      founders: ["Dave Teare", "Roustem Karimov"],
      ownership: "Private",
      employees: "500+",
      customers: "150,000+",
      industries: ["Technology", "Security"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: true,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for vault management, item CRUD, and user provisioning",
      automation: true,
      automationDescription: "CLI and Connect server for secrets automation in CI/CD pipelines",
      permissions: true,
      permissionsDescription: "Vault-based access control with custom roles and group policies",
      auditLogs: true,
      auditLogsDescription: "Activity logging for vault access, item sharing, and admin actions",
      backup: true,
      backupDescription: "Encrypted vault backups with Emergency Kit recovery PDF",
      offlineSupport: true,
      offlineSupportDescription: "Full offline access to cached vaults on desktop and mobile",
      reporting: true,
      reportingDescription: "Usage reports and Watchtower security dashboard",
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      saml: true,
      samlDescription: "SAML 2.0 and OIDC SSO integration",
      sso: true,
      ssoDescription: "Okta, Azure AD, OneLogin, JumpCloud SCIM provisioning",
      mfa: true,
      mfaDescription: "TOTP authenticator, hardware key support, biometric unlock",
      encryption: "AES-256-GCM with Secret Key + SRP protocol",
      dataResidency: ["United States", "Canada", "European Union", "Australia", "Japan"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://1password.com/security",
    },
    pricing: [
      { plan: "Teams", billing: "Monthly", price: 19.95, currency: "USD", unit: "per team (up to 10 users)", highlighted: false },
      { plan: "Business", billing: "Annual", price: 7.99, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with dedicated support", highlighted: false },
    ],
    integrations: ["okta", "azure-ad", "onelogin", "jumpcloud", "github", "gitlab", "slack"],
    useCases: {
      primary: ["Password management", "Identity security", "Credential management"],
      secondary: ["DevOps secrets automation", "Compliance reporting"],
      idealCompanySize: ["50-500 employees"],
      bestIndustries: ["Legal", "Accounting", "Healthcare", "Technology"],
      typicalTeams: ["IT", "Security", "Engineering", "Executive"],
      commonWorkflows: ["Employee onboarding/offboarding", "Audit preparation", "International travel security"],
      migrationScenarios: ["Migrate from LastPass", "Migrate from Bitwarden", "Migrate from Dashlane"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "bitwarden": {
    slug: "bitwarden",
    name: "Bitwarden",
    company: {
      legalName: "Bitwarden Inc.",
      website: "https://bitwarden.com",
      founded: 2015,
      headquarters: "Santa Barbara, California, USA",
      founders: ["Kyle Spearrin", "Pranav Mishra"],
      ownership: "Private",
      employees: "100+",
      customers: "10,000,000+",
      industries: ["Technology", "Security"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "Linux", "iOS", "Android"],
      mobileApps: true,
      browserExtension: true,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API and SDK for integration",
      automation: true,
      automationDescription: "CLI tool for secrets management",
      permissions: true,
      permissionsDescription: "Collection-based access control with user and group permissions",
      auditLogs: true,
      auditLogsDescription: "Event logs for organization actions",
      backup: true,
      backupDescription: "Encrypted export with self-hosting option for full data control",
      offlineSupport: true,
      offlineSupportDescription: "Offline access to cached vault on all clients",
      templates: true,
      templatesDescription: "Pre-built item templates for common credential types",
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      saml: true,
      samlDescription: "SAML 2.0 SSO on Enterprise plans",
      sso: true,
      ssoDescription: "OIDC and SAML integration",
      mfa: true,
      mfaDescription: "TOTP, Duo, YubiKey, FIDO2 WebAuthn",
      encryption: "AES-256-bit end-to-end encryption",
      dataResidency: ["United States", "European Union"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://bitwarden.com/security",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Families", billing: "Annual", price: 3.33, currency: "USD", unit: "per month (up to 6 users)", highlighted: false },
      { plan: "Teams", billing: "Annual", price: 3.33, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Enterprise", billing: "Annual", price: 5.00, currency: "USD", unit: "per user/month", highlighted: true },
    ],
    integrations: ["okta", "azure-ad", "onelogin", "google-workspace"],
    useCases: {
      primary: ["Password management", "Credential sharing"],
      secondary: ["Self-hosted security", "Compliance management"],
      idealCompanySize: ["1-1000 employees"],
      bestIndustries: ["Technology", "Healthcare", "Education", "Government"],
      typicalTeams: ["IT", "Security", "Engineering"],
      commonWorkflows: ["Team credential sharing", "Self-hosted deployment"],
      migrationScenarios: ["Migrate from LastPass", "Migrate from 1Password"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "slack": {
    slug: "slack",
    name: "Slack",
    company: {
      legalName: "Slack Technologies, LLC",
      website: "https://slack.com",
      founded: 2013,
      headquarters: "San Francisco, California, USA",
      founders: ["Stewart Butterfield", "Eric Costello", "Cal Henderson", "Serguei Mourachov"],
      ownership: "Subsidiary",
      parentCompany: "Salesforce",
      employees: "2,500+",
      customers: "100,000+",
      industries: ["Technology", "Communication"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "Linux", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "Comprehensive REST and Events API for messaging, files, and workflows",
      webhooks: true,
      webhooksDescription: "Incoming and outgoing webhooks for external service integration",
      automation: true,
      automationDescription: "Workflow Builder for no-code automation",
      marketplace: true,
      marketplaceDescription: "Slack App Directory with 2,600+ integrations",
      collaboration: true,
      collaborationDescription: "Channels, threads, huddles, and canvases for team collaboration",
      analytics: true,
      analyticsDescription: "Channel analytics, message activity, and adoption metrics",
      permissions: true,
      permissionsDescription: "Workspace and channel-level permissions with guest roles",
      auditLogs: true,
      auditLogsDescription: "Enterprise Grid audit log API and dashboard",
      backup: false,
      offlineSupport: true,
      offlineSupportDescription: "Message history available offline on desktop and mobile",
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: false,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Google, and Apple SSO",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware keys",
      encryption: "AES-256 at rest, TLS 1.2+ in transit",
      dataResidency: ["United States", "European Union", "Australia", "Japan", "Canada"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://slack.com/trust",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Pro", billing: "Annual", price: 7.25, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Business+", billing: "Annual", price: 12.50, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Enterprise Grid", billing: "Custom", description: "Custom pricing for large organizations", highlighted: false },
    ],
    integrations: ["google-drive", "zoom", "notion", "github", "jira", "asana", "figma", "zapier", "microsoft-teams", "linear"],
    useCases: {
      primary: ["Team communication", "Channel-based messaging"],
      secondary: ["Workflow automation", "Knowledge management"],
      idealCompanySize: ["10-10,000 employees"],
      bestIndustries: ["Technology", "Media", "Financial Services", "Healthcare"],
      typicalTeams: ["Engineering", "Marketing", "Sales", "Support", "Operations"],
      commonWorkflows: ["Incident response", "Customer support ticketing", "Deploy notifications"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "notion": {
    slug: "notion",
    name: "Notion",
    company: {
      legalName: "Notion Labs, Inc.",
      website: "https://notion.so",
      founded: 2013,
      headquarters: "San Francisco, California, USA",
      founders: ["Ivan Zhao", "Simon Last"],
      ownership: "Private",
      employees: "500+",
      customers: "100,000,000+",
      industries: ["Technology", "Productivity"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: true,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for pages, databases, and user management",
      webhooks: true,
      webhooksDescription: "Webhook integrations via Zapier, Make, and custom solutions",
      automation: true,
      automationDescription: "Notion Automations for database triggers and actions",
      templates: true,
      templatesDescription: "Extensive template gallery with community submissions",
      collaboration: true,
      collaborationDescription: "Real-time collaborative editing with comments and mentions",
      analytics: false,
      permissions: true,
      permissionsDescription: "Page-level, database-level, and workspace-level permissions",
      auditLogs: true,
      auditLogsDescription: "Workspace audit log on Business and Enterprise plans",
      backup: true,
      backupDescription: "Export all workspace content as Markdown, HTML, or CSV",
      versionHistory: true,
      versionHistoryDescription: "30-day version history on Free plan, unlimited on paid plans",
      offlineSupport: true,
      offlineSupportDescription: "Offline access to recently viewed pages on desktop and mobile",
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: true,
      samlDescription: "SAML 2.0 SSO on Business and Enterprise plans",
      sso: true,
      ssoDescription: "SAML, OIDC, Google Workspace SSO",
      mfa: true,
      mfaDescription: "TOTP two-factor authentication",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union", "Japan", "Australia"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://notion.so/security",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Plus", billing: "Annual", price: 10, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Business", billing: "Annual", price: 18, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with advanced controls", highlighted: false },
    ],
    integrations: ["slack", "google-drive", "figma", "github", "jira", "asana", "trello", "zapier", "make"],
    useCases: {
      primary: ["Knowledge management", "Project documentation", "Wiki"],
      secondary: ["Project management", "Database", "CRM"],
      idealCompanySize: ["1-500 employees"],
      bestIndustries: ["Technology", "Education", "Media", "Design"],
      typicalTeams: ["Engineering", "Product", "Marketing", "Design", "HR"],
      commonWorkflows: ["Meeting notes", "Product documentation", "OKR tracking", "Content calendar"],
      migrationScenarios: ["Migrate from Confluence", "Migrate from Evernote"],
      beginnerSuitability: "High",
      enterpriseSuitability: "Medium",
    },
  },

  "figma": {
    slug: "figma",
    name: "Figma",
    company: {
      legalName: "Figma, Inc.",
      website: "https://figma.com",
      founded: 2012,
      headquarters: "San Francisco, California, USA",
      founders: ["Dylan Field", "Evan Wallace"],
      ownership: "Private",
      employees: "1,000+",
      customers: "4,000,000+",
      industries: ["Technology", "Design"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for file access, components, and plugin management",
      automation: true,
      automationDescription: "Plugin API for workflow automation and design tokens",
      collaboration: true,
      collaborationDescription: "Real-time multiplayer editing with comments and version history",
      templates: true,
      templatesDescription: "Community template library and design system starter kits",
      permissions: true,
      permissionsDescription: "Team libraries, project-level permissions, and shared plugins",
      versionHistory: true,
      versionHistoryDescription: "Full version history with named versions and branch-based collaboration",
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, and Google SSO",
      mfa: true,
      mfaDescription: "TOTP and hardware security key support",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://figma.com/security",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Professional", billing: "Annual", price: 12, currency: "USD", unit: "per editor/month", highlighted: true },
      { plan: "Organization", billing: "Annual", price: 45, currency: "USD", unit: "per editor/month", highlighted: false },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with advanced security", highlighted: false },
    ],
    integrations: ["slack", "jira", "notion", "linear", "github", "gitlab", "zeplin", "storybook"],
    useCases: {
      primary: ["UI/UX design", "Prototyping", "Design systems"],
      secondary: ["Whiteboarding", "Design handoff", "Developer collaboration"],
      idealCompanySize: ["5-5000 employees"],
      bestIndustries: ["Technology", "Design", "Media", "E-commerce"],
      typicalTeams: ["Design", "Product", "Engineering", "Marketing"],
      commonWorkflows: ["Screen design", "Design system management", "Developer handoff"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "linear": {
    slug: "linear",
    name: "Linear",
    company: {
      legalName: "Linear Orbit, Inc.",
      website: "https://linear.app",
      founded: 2019,
      headquarters: "San Francisco, California, USA",
      founders: ["Karri Saarinen", "Jori Lallo", "Tuomas Artman"],
      ownership: "Private",
      employees: "50+",
      customers: "10,000+",
      industries: ["Technology", "Project Management"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "GraphQL API for issues, projects, cycles, and teams",
      webhooks: true,
      webhooksDescription: "Webhooks for issue creation, updates, and workflow triggers",
      automation: true,
      automationDescription: "Auto-assignment, triage, and workflow automation rules",
      templates: true,
      templatesDescription: "Issue templates for standardized bug reports and feature requests",
      collaboration: true,
      collaborationDescription: "Team-based projects with comments, cycles, and roadmaps",
      analytics: true,
      analyticsDescription: "Cycle analytics, velocity tracking, and burndown charts",
      permissions: true,
      permissionsDescription: "Team-based permissions with guest access",
      auditLogs: false,
      offlineSupport: true,
      offlineSupportDescription: "Offline access to cached issues on desktop app",
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0 and Google SSO",
      mfa: true,
      mfaDescription: "TOTP two-factor authentication",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://linear.app/security",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Team", billing: "Annual", price: 8, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Organization", billing: "Annual", price: 14, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with SSO, audit logs, and dedicated support", highlighted: false },
    ],
    integrations: ["slack", "github", "gitlab", "figma", "sentry", "zapier"],
    useCases: {
      primary: ["Issue tracking", "Project management", "Product development"],
      secondary: ["Sprint planning", "Bug tracking", "Roadmap management"],
      idealCompanySize: ["5-200 employees"],
      bestIndustries: ["Technology", "SaaS", "E-commerce"],
      typicalTeams: ["Engineering", "Product", "Design"],
      commonWorkflows: ["Sprint planning", "Bug triage", "Feature tracking", "Cycle retrospectives"],
      beginnerSuitability: "Medium",
      enterpriseSuitability: "Medium",
    },
  },

  "asana": {
    slug: "asana",
    name: "Asana",
    company: {
      legalName: "Asana, Inc.",
      website: "https://asana.com",
      founded: 2008,
      headquarters: "San Francisco, California, USA",
      founders: ["Dustin Moskovitz", "Justin Rosenstein"],
      ownership: "Public",
      employees: "1,800+",
      customers: "139,000+",
      industries: ["Technology", "Project Management"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for tasks, projects, portfolios, and users",
      webhooks: true,
      webhooksDescription: "Webhooks for task changes and project updates",
      automation: true,
      automationDescription: "Asana Intelligence rules, templates, and approval workflows",
      templates: true,
      templatesDescription: "Project templates for common workflows across departments",
      collaboration: true,
      collaborationDescription: "Tasks with comments, mentions, and real-time updates",
      analytics: true,
      analyticsDescription: "Portfolio dashboards, workload view, and goals tracking",
      permissions: true,
      permissionsDescription: "Project-level and team-level permissions with guest access",
      auditLogs: true,
      auditLogsDescription: "Admin console with audit log API on Enterprise plans",
      reporting: true,
      reportingDescription: "Custom dashboards, workload reports, and goal tracking",
      offlineSupport: true,
      offlineSupportDescription: "Offline access on desktop and mobile apps",
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, and Google SSO",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware security keys",
      encryption: "AES-256 at rest, TLS 1.2+ in transit",
      dataResidency: ["United States", "European Union", "Japan", "Australia"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://asana.com/security",
    },
    pricing: [
      { plan: "Personal", billing: "Annual", price: 0, currency: "USD", unit: "unlimited users", highlighted: false },
      { plan: "Starter", billing: "Annual", price: 10.99, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Advanced", billing: "Annual", price: 30.49, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with advanced admin and security", highlighted: false },
    ],
    integrations: ["slack", "jira", "figma", "google-drive", "microsoft-teams", "zapier", "salesforce"],
    useCases: {
      primary: ["Project management", "Task tracking", "Workflow management"],
      secondary: ["Goal tracking", "Portfolio management", "Resource planning"],
      idealCompanySize: ["10-5000 employees"],
      bestIndustries: ["Technology", "Professional Services", "Marketing", "Education"],
      typicalTeams: ["Marketing", "Operations", "Engineering", "Product", "HR"],
      commonWorkflows: ["Campaign management", "Product launches", "OKR tracking"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "jira": {
    slug: "jira",
    name: "Jira",
    company: {
      legalName: "Atlassian Corporation",
      website: "https://atlassian.com/software/jira",
      founded: 2002,
      headquarters: "Sydney, Australia",
      founders: ["Mike Cannon-Brookes", "Scott Farquhar"],
      ownership: "Public",
      employees: "12,000+",
      customers: "200,000+",
      industries: ["Technology", "Software Development"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API and GraphQL for issues, projects, workflows, and automation",
      webhooks: true,
      webhooksDescription: "Webhooks for issue events, project changes, and workflow transitions",
      automation: true,
      automationDescription: "Atlassian Intelligence with no-code automation rules",
      marketplace: true,
      marketplaceDescription: "Atlassian Marketplace with 5,000+ apps",
      templates: true,
      templatesDescription: "Project templates for Scrum, Kanban, bug tracking, and team-managed projects",
      collaboration: true,
      collaborationDescription: "Team collaboration with comments, mentions, and shared dashboards",
      analytics: true,
      analyticsDescription: "Reports, dashboards, and backlog insights",
      permissions: true,
      permissionsDescription: "Project-level, issue-level, and global permissions with permission schemes",
      auditLogs: true,
      auditLogsDescription: "Admin audit log with Atlassian Access",
      backup: true,
      backupDescription: "XML backup and cloud-to-cloud migration",
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: false,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Google Workspace, and Microsoft Entra ID",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware keys via Atlassian Access",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union", "Australia", "Germany", "France", "United Kingdom", "Canada", "Japan", "Singapore"],
      sla: "99.9% uptime SLA",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://atlassian.com/trust",
    },
    pricing: [
      { plan: "Free", billing: "Annual", price: 0, currency: "USD", unit: "up to 10 users", highlighted: false },
      { plan: "Standard", billing: "Annual", price: 7.75, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Premium", billing: "Annual", price: 15.25, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with 99.99% SLA and unlimited automation", highlighted: false },
    ],
    integrations: ["slack", "confluence", "github", "gitlab", "bitbucket", "figma", "zapier", "microsoft-teams", "sentry"],
    useCases: {
      primary: ["Issue tracking", "Bug tracking", "Agile project management"],
      secondary: ["Scrum boards", "Kanban boards", "Roadmap planning"],
      idealCompanySize: ["10-10,000 employees"],
      bestIndustries: ["Technology", "Financial Services", "Government", "Healthcare"],
      typicalTeams: ["Engineering", "IT", "Support", "Product"],
      commonWorkflows: ["Sprint planning", "Bug triage", "Release management", "IT service desk"],
      beginnerSuitability: "Medium",
      enterpriseSuitability: "High",
    },
  },

  "salesforce": {
    slug: "salesforce",
    name: "Salesforce",
    company: {
      legalName: "Salesforce, Inc.",
      website: "https://salesforce.com",
      founded: 1999,
      headquarters: "San Francisco, California, USA",
      founders: ["Marc Benioff", "Parker Harris", "Dave Moellenhoff", "Frank Dominguez"],
      ownership: "Public",
      employees: "73,000+",
      customers: "150,000+",
      industries: ["Technology", "CRM"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "Comprehensive REST, SOAP, GraphQL, and Bulk APIs",
      webhooks: true,
      webhooksDescription: "Apex triggers, Platform Events, and external webhook integrations",
      automation: true,
      automationDescription: "Flow Builder, Process Builder, and Apex automations",
      marketplace: true,
      marketplaceDescription: "AppExchange with 5,000+ apps",
      templates: true,
      templatesDescription: "Salesforce Accelerator templates for industry solutions",
      collaboration: true,
      collaborationDescription: "Chatter social collaboration and Quip document collaboration",
      analytics: true,
      analyticsDescription: "Tableau CRM, Einstein Analytics, and report builder",
      permissions: true,
      permissionsDescription: "Role-based, profile-based, and permission set access control",
      auditLogs: true,
      auditLogsDescription: "Setup audit trail, login history, and Event Monitoring",
      backup: true,
      backupDescription: "Data Export Service and third-party backup solutions",
      offlineSupport: true,
      offlineSupportDescription: "Salesforce Mobile offline mode with selective sync",
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Microsoft Entra ID, Google Workspace",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware keys, biometric",
      encryption: "AES-256 at rest, TLS 1.2 in transit, Shield Platform Encryption",
      dataResidency: ["United States", "European Union", "United Kingdom", "Australia", "Japan", "Canada", "France", "Germany", "India", "Singapore", "South Korea"],
      sla: "99.99% core SLA",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://salesforce.com/company/privacy",
    },
    integrations: ["slack", "microsoft-teams", "gmail", "outlook", "hubspot", "zapier", "tableau", "mulesoft"],
    useCases: {
      primary: ["CRM", "Sales management", "Customer service"],
      secondary: ["Marketing automation", "Analytics", "App development"],
      idealCompanySize: ["50-50,000 employees"],
      bestIndustries: ["Financial Services", "Healthcare", "Technology", "Manufacturing", "Retail"],
      typicalTeams: ["Sales", "Marketing", "Service", "Operations"],
      commonWorkflows: ["Lead management", "Opportunity tracking", "Case management", "Campaign analytics"],
      beginnerSuitability: "Low",
      enterpriseSuitability: "High",
    },
  },

  "hubspot": {
    slug: "hubspot",
    name: "HubSpot",
    company: {
      legalName: "HubSpot, Inc.",
      website: "https://hubspot.com",
      founded: 2006,
      headquarters: "Cambridge, Massachusetts, USA",
      founders: ["Brian Halligan", "Dharmesh Shah"],
      ownership: "Public",
      employees: "7,400+",
      customers: "205,000+",
      industries: ["Technology", "Marketing", "CRM", "Sales"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for CRM, marketing, sales, and service hubs",
      webhooks: true,
      webhooksDescription: "Webhook subscriptions for CRM events and form submissions",
      automation: true,
      automationDescription: "Workflow automation for marketing, sales, and service sequences",
      marketplace: true,
      marketplaceDescription: "HubSpot App Marketplace with 1,500+ integrations",
      templates: true,
      templatesDescription: "Email, landing page, and form templates across hubs",
      collaboration: true,
      collaborationDescription: "Shared inbox, team email, and deal team collaboration",
      analytics: true,
      analyticsDescription: "Custom dashboards, attribution reports, and revenue analytics",
      permissions: true,
      permissionsDescription: "User roles, team-based access, and object-level permissions",
      auditLogs: true,
      auditLogsDescription: "Login history, content audit, and permission change logs",
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Google Workspace, Microsoft Entra ID",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware security keys",
      encryption: "AES-256 at rest, TLS 1.2+ in transit",
      dataResidency: ["United States", "European Union", "Australia"],
      sla: "99.9% uptime",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://hubspot.com/security",
    },
    integrations: ["salesforce", "slack", "gmail", "outlook", "zapier", "wordpress", "shopify"],
    useCases: {
      primary: ["CRM", "Inbound marketing", "Sales automation"],
      secondary: ["Customer service", "Content management", "Analytics"],
      idealCompanySize: ["10-2,000 employees"],
      bestIndustries: ["Technology", "Professional Services", "E-commerce", "Education"],
      typicalTeams: ["Marketing", "Sales", "Service", "Operations"],
      commonWorkflows: ["Lead nurturing", "Email marketing campaigns", "Deal pipeline management", "Customer onboarding"],
      beginnerSuitability: "High",
      enterpriseSuitability: "Medium",
    },
  },

  "github": {
    slug: "github",
    name: "GitHub",
    company: {
      legalName: "GitHub, Inc.",
      website: "https://github.com",
      founded: 2008,
      headquarters: "San Francisco, California, USA",
      founders: ["Tom Preston-Werner", "Chris Wanstrath", "PJ Hyett"],
      ownership: "Subsidiary",
      parentCompany: "Microsoft",
      employees: "3,000+",
      customers: "100,000,000+",
      industries: ["Technology", "Software Development"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST and GraphQL API for repositories, issues, actions, and packages",
      webhooks: true,
      webhooksDescription: "Webhooks for repository events, pull requests, and releases",
      automation: true,
      automationDescription: "GitHub Actions for CI/CD, issue automation, and code quality",
      marketplace: true,
      marketplaceDescription: "GitHub Marketplace with CI/CD, code quality, and monitoring apps",
      templates: true,
      templatesDescription: "Repository templates, issue templates, and starter workflows",
      collaboration: true,
      collaborationDescription: "Pull requests, code reviews, discussions, and projects",
      analytics: true,
      analyticsDescription: "Insights, contributor graphs, and traffic analytics",
      permissions: true,
      permissionsDescription: "Repository roles, team-based access, and branch protection rules",
      auditLogs: true,
      auditLogsDescription: "Audit log for organization and enterprise accounts",
      backup: true,
      backupDescription: "Repository cloning, archive, and third-party backup integrations",
      offlineSupport: true,
      offlineSupportDescription: "Git operations work fully offline with sync on reconnect",
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Microsoft Entra ID, Google Workspace",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware security keys, passkeys",
      encryption: "AES-256 at rest, TLS 1.2+ in transit",
      dataResidency: ["United States", "European Union", "Australia", "Japan"],
      sla: "99.9% uptime SLA for GitHub Enterprise",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://github.com/security",
    },
    integrations: ["slack", "jira", "linear", "vercel", "netlify", "docker", "aws", "azure", "google-cloud"],
    useCases: {
      primary: ["Version control", "Code hosting", "CI/CD"],
      secondary: ["Code review", "Project management", "Package registry"],
      idealCompanySize: ["1-10,000 employees"],
      bestIndustries: ["Technology", "SaaS", "Financial Services", "Gaming"],
      typicalTeams: ["Engineering", "DevOps", "Security", "Product"],
      commonWorkflows: ["Pull request review", "CI/CD pipeline", "Code scanning", "Dependency management"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "gitlab": {
    slug: "gitlab",
    name: "GitLab",
    company: {
      legalName: "GitLab Inc.",
      website: "https://gitlab.com",
      founded: 2011,
      headquarters: "San Francisco, California, USA",
      founders: ["Dmitriy Zaporozhets", "Sid Sijbrandij"],
      ownership: "Public",
      employees: "2,000+",
      customers: "100,000+",
      industries: ["Technology", "DevOps"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST and GraphQL API for entire DevOps lifecycle",
      webhooks: true,
      webhooksDescription: "Webhooks for push, merge request, pipeline, and release events",
      automation: true,
      automationDescription: "GitLab CI/CD with auto DevOps and pipeline automation",
      templates: true,
      templatesDescription: "CI/CD templates, group-level project templates, and issue templates",
      collaboration: true,
      collaborationDescription: "Merge requests, code review, discussions, and epics",
      analytics: true,
      analyticsDescription: "DevOps reports, value stream analytics, and code quality trends",
      permissions: true,
      permissionsDescription: "Project, group, and instance-level permissions with custom roles",
      auditLogs: true,
      auditLogsDescription: "Instance and group audit events for compliance",
      backup: true,
      backupDescription: "Built-in backup and restore for self-managed instances",
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: false,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Google Workspace, Microsoft Entra ID",
      mfa: true,
      mfaDescription: "TOTP, WebAuthn, hardware keys",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union", "Australia", "United Kingdom"],
      sla: "99.95% uptime SLA for Premium and Ultimate",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://gitlab.com/security",
    },
    integrations: ["slack", "jira", "kubernetes", "docker", "aws", "google-cloud", "azure", "prometheus"],
    useCases: {
      primary: ["DevOps lifecycle", "CI/CD", "Source code management"],
      secondary: ["DevSecOps", "Package registry", "Infrastructure as code"],
      idealCompanySize: ["10-10,000 employees"],
      bestIndustries: ["Technology", "Financial Services", "Government", "Healthcare"],
      typicalTeams: ["Engineering", "DevOps", "Security"],
      commonWorkflows: ["CI/CD pipeline", "Code review", "Compliance scanning", "Release management"],
      beginnerSuitability: "Medium",
      enterpriseSuitability: "High",
    },
  },

  "vercel": {
    slug: "vercel",
    name: "Vercel",
    company: {
      legalName: "Vercel Inc.",
      website: "https://vercel.com",
      founded: 2015,
      headquarters: "San Francisco, California, USA",
      founders: ["Guillermo Rauch"],
      ownership: "Private",
      employees: "500+",
      customers: "1,000,000+",
      industries: ["Technology", "Cloud Computing"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for deployments, projects, domains, and teams",
      webhooks: true,
      webhooksDescription: "Deployment and git event webhooks",
      automation: true,
      automationDescription: "Automatic deployments, preview environments, and git integration",
      templates: true,
      templatesDescription: "Starter templates for frameworks including Next.js, Svelte, Nuxt",
      collaboration: true,
      collaborationDescription: "Team projects with role-based access and comments on previews",
      analytics: true,
      analyticsDescription: "Web Analytics and Speed Insights",
      permissions: true,
      permissionsDescription: "Team roles, project-level access, and SAML directory groups",
      auditLogs: true,
      auditLogsDescription: "Audit logs on Enterprise plan",
      backup: false,
    },
    security: {
      soc2: true,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0 and OIDC on Enterprise plan",
      mfa: true,
      mfaDescription: "TOTP and hardware security keys",
      encryption: "AES-256 at rest, TLS 1.3 in transit",
      dataResidency: ["United States", "European Union"],
      sla: "99.99% uptime for Enterprise",
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://vercel.com/security",
    },
    pricing: [
      { plan: "Hobby", billing: "Annual", price: 0, currency: "USD", unit: "personal projects", highlighted: false },
      { plan: "Pro", billing: "Annual", price: 20, currency: "USD", unit: "per user/month", highlighted: true },
      { plan: "Team", billing: "Annual", price: 100, currency: "USD", unit: "per user/month", highlighted: false },
      { plan: "Enterprise", billing: "Custom", description: "Custom pricing with dedicated support", highlighted: false },
    ],
    integrations: ["github", "gitlab", "slack", "sentry", "datadog", "sanity", "contentful"],
    useCases: {
      primary: ["Frontend deployment", "Serverless functions", "Static site hosting"],
      secondary: ["Edge functions", "Preview deployments", "Analytics"],
      idealCompanySize: ["1-500 employees"],
      bestIndustries: ["Technology", "SaaS", "E-commerce", "Media"],
      typicalTeams: ["Frontend Engineering", "Design", "Product"],
      commonWorkflows: ["Deploy from git", "Preview deployments", "Edge-rendered applications"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },

  "stripe": {
    slug: "stripe",
    name: "Stripe",
    company: {
      legalName: "Stripe, Inc.",
      website: "https://stripe.com",
      founded: 2010,
      headquarters: "San Francisco, California, USA",
      founders: ["Patrick Collison", "John Collison"],
      ownership: "Private",
      employees: "8,000+",
      customers: "1,000,000+",
      industries: ["Technology", "Financial Services"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: true,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for payments, subscriptions, connected accounts, and data",
      webhooks: true,
      webhooksDescription: "Webhook events for payment lifecycle, disputes, and account changes",
      automation: true,
      automationDescription: "Stripe Workflows for automated payment operations",
      marketplace: true,
      marketplaceDescription: "Stripe App Marketplace for extensions and integrations",
      templates: false,
      collaboration: false,
      analytics: true,
      analyticsDescription: "Stripe Sigma SQL analytics, reporting, and dashboard",
      permissions: true,
      permissionsDescription: "Team roles, API key scoping, and granular user permissions",
      auditLogs: true,
      auditLogsDescription: "API request logs and account activity audit trail",
      backup: false,
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      pciDss: true,
      saml: false,
      sso: false,
      mfa: true,
      mfaDescription: "TOTP and hardware security keys",
      encryption: "AES-256 at rest, TLS in transit, PGP for email",
      dataResidency: ["United States", "European Union", "Canada", "Australia", "Singapore", "Japan"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://stripe.com/security",
    },
    integrations: ["salesforce", "hubspot", "shopify", "woocommerce", "zapier", "quickbooks", "xero"],
    useCases: {
      primary: ["Payment processing", "Subscription management", "E-commerce payments"],
      secondary: ["Marketplace payments", "Platform revenue share", "Global payments"],
      idealCompanySize: ["1-10,000 employees"],
      bestIndustries: ["E-commerce", "SaaS", "Financial Services", "Marketplace"],
      typicalTeams: ["Engineering", "Finance", "Operations"],
      commonWorkflows: ["Checkout integration", "Subscription billing", "Payout management"],
      beginnerSuitability: "Medium",
      enterpriseSuitability: "High",
    },
  },

  "docker": {
    slug: "docker",
    name: "Docker",
    company: {
      legalName: "Docker, Inc.",
      website: "https://docker.com",
      founded: 2010,
      headquarters: "Palo Alto, California, USA",
      founders: ["Kamran Khan", "Solomon Hykes", "Sebastien Pahl"],
      ownership: "Private",
      employees: "500+",
      customers: "20,000,000+",
      industries: ["Technology", "DevOps"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "Linux"],
      mobileApps: false,
      browserExtension: false,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "Docker Engine API and Docker Hub Registry API",
      webhooks: true,
      webhooksDescription: "Docker Hub and Docker Registry webhooks for push events",
      automation: true,
      automationDescription: "Docker Compose, Dockerfile, and Docker Build automations",
      marketplace: true,
      marketplaceDescription: "Docker Hub with official and community images",
      templates: true,
      templatesDescription: "Docker starter repos and compose samples",
      collaboration: true,
      collaborationDescription: "Docker Hub teams and organizations with access control",
      analytics: false,
      permissions: true,
      permissionsDescription: "Docker Hub organization roles and repository-level access",
      auditLogs: false,
      backup: false,
      offlineSupport: true,
      offlineSupportDescription: "Docker images cached locally, offline engine operation",
    },
    security: {
      soc2: false,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: false,
      sso: true,
      ssoDescription: "OIDC SSO on Docker Business plan",
      mfa: true,
      mfaDescription: "TOTP and hardware security keys",
      encryption: "TLS in transit, image signing via Docker Content Trust",
      dataResidency: ["United States", "European Union"],
      penetrationTesting: false,
      bugBounty: true,
      securityPage: "https://docker.com/trust",
    },
    integrations: ["github", "gitlab", "kubernetes", "aws", "azure", "google-cloud", "jenkins", "circleci"],
    useCases: {
      primary: ["Containerization", "Application packaging", "Development environments"],
      secondary: ["Microservices", "CI/CD pipelines", "Cloud migration"],
      idealCompanySize: ["1-5,000 employees"],
      bestIndustries: ["Technology", "SaaS", "Financial Services", "Media"],
      typicalTeams: ["Engineering", "DevOps", "Platform Engineering"],
      commonWorkflows: ["Dockerfile build", "Container deployment", "Development environment setup"],
      beginnerSuitability: "Medium",
      enterpriseSuitability: "High",
    },
  },

  "supabase": {
    slug: "supabase",
    name: "Supabase",
    company: {
      legalName: "Supabase, Inc.",
      website: "https://supabase.com",
      founded: 2020,
      headquarters: "San Francisco, California, USA",
      founders: ["Paul Copplestone", "Ant Wilson"],
      ownership: "Private",
      employees: "50+",
      customers: "1,000,000+",
      industries: ["Technology", "Database", "Cloud Computing"],
      targetAudience: "All",
      platforms: ["Web", "iOS", "Android"],
      mobileApps: false,
      browserExtension: false,
      desktopApp: false,
    },
    capabilities: {
      api: true,
      apiDescription: "REST, GraphQL, and Realtime APIs auto-generated from database schema",
      webhooks: true,
      webhooksDescription: "Database webhooks for insert, update, delete events",
      automation: true,
      automationDescription: "Edge Functions for server-side logic",
      templates: true,
      templatesDescription: "Starter templates for Next.js, React, Flutter, and Svelte",
      collaboration: true,
      collaborationDescription: "Team-based project access with role management",
      analytics: false,
      permissions: true,
      permissionsDescription: "Row-level security via PostgreSQL policies",
      auditLogs: false,
      backup: true,
      backupDescription: "Daily backups on Pro plan, point-in-time recovery on Team plan",
      offlineSupport: false,
    },
    security: {
      soc2: false,
      iso27001: false,
      gdpr: true,
      hipaa: false,
      ccpa: true,
      saml: false,
      sso: false,
      mfa: true,
      mfaDescription: "TOTP two-factor authentication",
      encryption: "AES-256 at rest, TLS in transit",
      dataResidency: ["United States", "European Union", "Asia Pacific"],
      penetrationTesting: false,
      bugBounty: true,
      securityPage: "https://supabase.com/security",
    },
    integrations: ["vercel", "netlify", "github", "zapier", "stripe"],
    useCases: {
      primary: ["Backend as a service", "Database hosting", "Realtime applications"],
      secondary: ["Authentication", "File storage", "Edge functions"],
      idealCompanySize: ["1-200 employees"],
      bestIndustries: ["Technology", "SaaS", "E-commerce"],
      typicalTeams: ["Engineering", "Full-stack development"],
      commonWorkflows: ["Database-driven API development", "Realtime features", "User authentication"],
      beginnerSuitability: "High",
      enterpriseSuitability: "Medium",
    },
  },

  "zoom": {
    slug: "zoom",
    name: "Zoom",
    company: {
      legalName: "Zoom Communications, Inc.",
      website: "https://zoom.us",
      founded: 2011,
      headquarters: "San Jose, California, USA",
      founders: ["Eric Yuan"],
      ownership: "Public",
      employees: "7,200+",
      customers: "300,000+",
      industries: ["Technology", "Communications"],
      targetAudience: "All",
      platforms: ["Web", "Windows", "macOS", "Linux", "iOS", "Android"],
      mobileApps: true,
      browserExtension: true,
      desktopApp: true,
    },
    capabilities: {
      api: true,
      apiDescription: "REST API for meetings, users, recordings, and webinars",
      webhooks: true,
      webhooksDescription: "Meeting events, recording completion, and user activity webhooks",
      automation: true,
      automationDescription: "Scheduling automation and workflow triggers",
      marketplace: true,
      marketplaceDescription: "Zoom App Marketplace with 2,000+ integrations",
      templates: false,
      collaboration: true,
      collaborationDescription: "HD video, chat, whiteboard, breakout rooms, and polling",
      analytics: true,
      analyticsDescription: "Usage dashboards, meeting quality reports, and adoption analytics",
      permissions: true,
      permissionsDescription: "Role-based admin controls and group management",
      auditLogs: true,
      auditLogsDescription: "Admin audit logs and meeting registration history",
      backup: false,
      offlineSupport: false,
    },
    security: {
      soc2: true,
      iso27001: true,
      gdpr: true,
      hipaa: true,
      ccpa: true,
      pciDss: false,
      saml: true,
      sso: true,
      ssoDescription: "SAML 2.0, OIDC, Google Workspace, Microsoft Entra ID",
      mfa: true,
      mfaDescription: "TOTP, SMS, hardware security keys",
      encryption: "AES-256-GCM for meetings, E2EE available",
      dataResidency: ["United States", "European Union", "Australia", "Japan", "Canada", "India", "Latin America"],
      penetrationTesting: true,
      bugBounty: true,
      securityPage: "https://zoom.com/trust",
    },
    integrations: ["slack", "microsoft-teams", "google-calendar", "outlook", "salesforce", "hubspot", "zapier"],
    useCases: {
      primary: ["Video conferencing", "Webinars", "Team meetings"],
      secondary: ["Phone system", "Chat", "Event management"],
      idealCompanySize: ["5-10,000 employees"],
      bestIndustries: ["Education", "Healthcare", "Financial Services", "Technology"],
      typicalTeams: ["All departments", "Remote teams", "Sales", "HR"],
      commonWorkflows: ["Daily standups", "Client meetings", "Webinars", "Virtual events"],
      beginnerSuitability: "High",
      enterpriseSuitability: "High",
    },
  },
}

export function getEntity(slug: string): SoftwareEntity | null {
  return entities[slug] ?? null
}

export function getAllEntities(): SoftwareEntity[] {
  return Object.values(entities)
}

export function getEntitiesByCategory(category: string): SoftwareEntity[] {
  return Object.values(entities).filter((e) => {
    const c = e.company
    return c?.industries?.some((i) => i.toLowerCase().includes(category.toLowerCase()))
  })
}

export function enrichReview<I extends { slug: string }>(review: I): I & { entity?: SoftwareEntity } {
  const entity = entities[review.slug]
  return entity ? { ...review, entity } : review
}

export function getAllEntitySlugs(): string[] {
  return Object.keys(entities)
}
